version: "3"

services:
  db:
   container_name: composepostgres
   image: postgres
   restart: always
   environment:
    - POSTGRES_USER=dev
    - POSTGRES_PASSWORD=dev
    - POSTGRES_DB=avito_products
   volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   ports:
    - '5432:5432'
  apiserver:
    build: .
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
